version: "3.9"
services:
  slack_store:
    container_name: slack_store
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
  ngrok:
    container_name: slack_ngrok
    image: ngrok/ngrok
    command: http 80
